# Copyright 2015-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: pgplot
  version: "5.2.2"

source:
  fn: pgplot5.2.tar.gz
  url: http://fossies.org/unix/misc/old/pgplot5.2.tar.gz
  md5: e8a6e8d0d5ef9d1709dfb567724525ae
  patches:
    - drivers.patch
    - gfortran.patch
    - png-setjmp.patch
    - prefix.patch
    - late-binding-drivers.patch
    - osx.patch #[osx]

build:
  number: 9
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - libpng
    - modern-xorg-stack
    - zlib
  run:
    - libgfortran 3.0.0 #[linux]
    - libpng
    - modern-xorg-stack
    - zlib

about:
  home: http://www.astro.caltech.edu/~tjp/pgplot/
  license: non-commercial use only
  summary: a FORTRAN plotting library
