# Copyright 2014-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# Some portions of astroquery use the 'keyring' module, but this isn't
# currently available in Anaconda's Python 3 stack. For now I've just disabled
# the dependency in that version, since it's not essential.

package:
  name: astroquery
  version: "0.3.1"

source:
  fn: astroquery-0.3.1.tar.gz
  url: https://pypi.python.org/packages/source/a/astroquery/astroquery-0.3.1.tar.gz
  md5: dc43227008568f0fa61cd03b76d74849
  patches:
    - no-auto-upgrade.patch

build:
  number: 0

requirements:
  build:
    - astropy
    - astropy-helpers
    - beautiful-soup
    - html5lib
    - keyring # [py2k]
    - python
    - requests
    - setuptools

  run:
    - astropy
    - beautiful-soup
    - html5lib
    - keyring # [py2k]
    - python
    - requests
    
test:
  imports:
    - astroquery

about:
  home: http://www.astropy.org/astroquery/
  license: BSD
  summary: Functions and classes to access online astronomical data resources
