# Copyright 2015-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# We don't provide the rfigui right now. It needs Gtk-- > 3.0, so it wouldn't
# be a huge amount of work to make that work since we have the Gtk+ 3 stack.
# We'd need libsigc++, glibmm, and gtkmm.

{% set name = "aoflagger" %}
{% set version = "2.9.0" %}
{% set sha256 = "753c8d3690c2b397f574c716b16b1794742c5a220b30d631734a4f94f333ebab" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://downloads.sourceforge.net/project/{{ name }}/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - mac-cxx.patch

build:
  number: 3
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cmake
    - boost 1.63.*
    - casacore 2.2.*
    - cfitsio 3.410
    - fftw 3.3.*
    - gsl 2.2.*
    - hdf5 1.8.18|1.8.18.*
    - libxml2 2.9.*
    - openblas 0.2.19|0.2.19.*
  run:
    - boost 1.63.*
    - casacore 2.2.*
    - cfitsio 3.410
    - fftw 3.3.*
    - gsl 2.2.*
    - hdf5 1.8.18|1.8.18.*
    - libxml2 2.9.*
    - openblas 0.2.19|0.2.19.*

about:
  home: http://aoflagger.sourceforge.net/
  license: GPLv3
  summary: automatic flagging of interference in radio astronomical data sets
