# Copyright 2014-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: atk
  version: 2.18.0

source:
  fn: atk-2.18.0.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/atk/2.18/atk-2.18.0.tar.xz
  sha256: ce6c48d77bf951083029d5a396dd552d836fff3c1715d3a7022e917e46d0c92b

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - glib 2.51.*
    - gobject-introspection 1.51.*
    - python
  run:
    - glib 2.51.*
    - gobject-introspection 1.51.*

about:
  home: http://www.gtk.org/
  license: LGPL
