# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# NOTE: if updating major or minor version, update `so-versioning.patch`.

package:
  name: casa-python
  version: "4.6.0"

source:
  svn_url: https://svn.cv.nrao.edu/svn/casa/branches/release-4_6/
  svn_rev: 36590
  svn_ignore_externals: yes
  patches:
    - so-versioning.patch
    - casadef.patch
    - ncursesw.patch

build:
  number: 3
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - casa-tools
    - cmake
    - libgfortran 3.0.0 #[linux]
    - ncurses
    - nomkl # speed by avoiding big download
    - python
    - rpfits
    - swig
  run:
    - casa-tools
    - libgfortran 3.0.0 #[linux]
    - ncurses
    - python
    - rpfits

about:
  home: http://casa.nrao.edu/
  license: GPL version 2
  summary: Python interfaces to the CASA tools
