# Copyright 2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: ds9
  version: "7.4.1"

source:
  fn: ds9.7.4.1.tar.gz
  url: http://ds9.si.edu/download/source/ds9.7.4.1.tar.gz
  sha256: 52ed71c1bb2174e0b2e4e5145135ac3d21d8f9e82d529c4577fcbc6034f49173
  patches:
    - extra-configure-args.patch

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - modern-xorg-stack
    - libxml2
    - libxslt
    - zlib
  run:
    - modern-xorg-stack
    - libxml2
    - libxslt
    - zlib

about:
  home: http://ds9.si.edu/
  license: GPLv3+
  summary: An astronomical imaging and data visualization application.
