# Copyright 2016-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set version = "7.5" %}
{% set sha256 = "8ae0876472aea2d1d616595f7efcedc4ad8f5edd249721b1e4929fe317ddee3e" %}

package:
  name: ds9
  version: {{ version }}

source:
  fn: ds9.{{ version }}.tar.gz
  url: http://ds9.si.edu/download/source/ds9.{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - extra-configure-args.patch

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - libxml2 2.9.*
    - libxslt 1.1.*
    - xorg-libx11 1.6.*
    - xorg-libxt 1.1*
    - xorg-xproto
    - zlib 1.2.*
  run:
    - libxml2 2.9.*
    - libxslt 1.1.*
    - xorg-libx11 1.6.*
    - xorg-libxt 1.1*
    - zlib 1.2.*

about:
  home: http://ds9.si.edu/
  license: GPLv3+
  summary: An astronomical imaging and data visualization application.
