# Copyright 2014-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# Unfortunately, we are limited in which Gtk+ versions we can support because
# we use Conda's version of Cairo. This is currently 1.12.18, while Gtk+
# versions >= 3.16 require Cairo >= 1.14.

package:
  name: gtk3
  version: "3.14.15"

source:
  fn: gtk+-3.14.15.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/gtk+/3.14/gtk+-3.14.15.tar.xz
  sha256: 3ac87659112ced9e5ee5bd55d055faa881aafd040f26ca40b0d8ba0fa6509c83
  patches:
    - m_pi.patch
    - no-module-warning.patch

build:
  number: 4
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - at-spi2-atk
    - atk
    - cairo-gobject
    - gdk-pixbuf
    - glib
    - gobject-introspection
    - modern-xorg-stack #[not osx]
    - pango 1.38.1 # make sure to get my pango with GI info, not stock Conda's
    - python
  run:
    - at-spi2-atk
    - atk
    - gdk-pixbuf
    - glib
    - gobject-introspection
    - modern-xorg-stack #[not osx]
    - pango 1.38.1 # make sure to get my pango with GI info, not stock Conda's

about:
  home: http://www.gtk.org/
  license: LGPL
  summary: version 3 of the Gtk+ graphical toolkit
