# Copyright 2014-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# NOTE: we locked on an older version of Gtk3 because of an old Cairo version
# in Anaconda defaults. This particular limitation is no longer relevant!

package:
  name: gtk3
  version: "3.14.15"

source:
  fn: gtk+-3.14.15.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/gtk+/3.14/gtk+-3.14.15.tar.xz
  sha256: 3ac87659112ced9e5ee5bd55d055faa881aafd040f26ca40b0d8ba0fa6509c83
  patches:
    - m_pi.patch
    - no-module-warning.patch

build:
  number: 1
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - at-spi2-atk 2.18.*
    - atk 2.18.*
    - cairo 1.14.*
    - gdk-pixbuf 2.32.*
    - glib 2.51.*
    - gobject-introspection 1.51.*
    - pango 1.40.*
    - python
    - xorg-libice 1.0.*  # [not osx]
    - xorg-libsm 1.2.*  # [not osx]
    - xorg-libx11 1.6.*  # [not osx]
    - xorg-libxrender 0.9.*  # [not osx]
    - xorg-xproto  # [not osx]
  run:
    - at-spi2-atk 2.18.*
    - atk 2.18.*
    - gdk-pixbuf 2.32.*
    - glib 2.51.*
    - gobject-introspection 1.51.*
    - pango 1.40.*
    - xorg-libice 1.0.*  # [not osx]
    - xorg-libsm 1.2.*  # [not osx]
    - xorg-libx11 1.6.*  # [not osx]
    - xorg-libxrender 0.9.*  # [not osx]

about:
  home: http://www.gtk.org/
  license: LGPL
  summary: version 3 of the Gtk+ graphical toolkit
