# Copyright 2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: iraf
  version: "2.16.1"

source:
  # Release:
  git_url: https://github.com/pkgw/iraf.git
  git_rev: 1dace4f0408ac98b1186684b8d3353f67ea2be49
  # Development:
  ## git_url: file:///work/repos/iraf
  ## git_rev: more-build-fixes

build:
  number: 2
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cfitsio
    - curl
    - expat
    - modern-xorg-stack
    - readline
  run:
    - cfitsio
    - curl
    - expat
    - modern-xorg-stack
    - readline

about:
  home: http://iraf.noao.edu/
  license: OpenSolaris CDDL, UCAR
  summary: The NOAO Image Reduction and Analysis Facility
