# Copyright 2016-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: iraf
  version: "2.16.1"

source:
  # Release:
  ## git_url: https://github.com/pkgw/iraf.git
  ## git_rev: cb835247ada85481e8dcca02b411217c3ea3adf4
  # Development:
  #git_url: file:///work/repos/iraf
  git_url: file:///home/peter/sw/conda/conda-recipes/repos/iraf
  git_rev: more-build-fixes

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cfitsio 3.*
    - curl 7.52.*
    - expat 2.1.*
    - readline 6.2*
    - xorg-gccmakedep
    - xorg-imake
    - xorg-libx11 1.6.*
    - xorg-xproto
  run:
    - cfitsio 3.*
    - curl 7.52.*
    - expat 2.1.*
    - readline 6.2*
    - xorg-libx11 1.6.*

about:
  home: http://iraf.noao.edu/
  license: OpenSolaris CDDL, UCAR
  summary: 'The NOAO Image Reduction and Analysis Facility.'
