# Copyright 2015-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# XXX: needs to be built in py2 for now since the patch contains non-ASCII
# and py3 conda-build can't handle that.

package:
  name: libsakura
  version: "2.0.0"

source:
  fn: libsakura-2.0.0.tar.gz
  url: https://svn.cv.nrao.edu/casa/devel/libsakura-2.0.0.tar.gz
  md5: 79014825c55a5073213a900f16b6a692
  patches:
    - compile-fixes.patch

build:
  number: 1
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cmake
    - eigen
    - fftw

about:
  home: http://alma.mtk.nao.ac.jp/j/
  license: GPL version 3
  summary: C++ library for fast image manipulations
