package:
  name: pytoml
  version: "0.1.10"

source:
  fn: pytoml-0.1.10.zip
  url: https://pypi.python.org/packages/cd/b0/9d41f4f2ffee340b91154ef3196187a3066a7b8eb386fd801f5c8dcda78e/pytoml-0.1.10.zip
  md5: 6c3522b47032dce6fe2c4cbbb288b985

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pytoml

about:
  home: http://github.com/avakar/pytoml
  license: MIT
  summary: A TOML-0.4.0 parser/writer for Python.
