# Copyright 2014-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# Shortcut to get new MD5 sum and URL:
#
#   curl -s https://pypi.python.org/pypi/pwkit/ |grep md5= |grep -v linux

package:
  name: pwkit
  version: "0.8.4"

source:
  fn: pwkit-0.8.4.tar.gz
  url: https://pypi.python.org/packages/8d/6e/eff751fcf3361191ac9b70b83791c933bf44c0bac3a0cc7d8bbd0ca02951/pwkit-0.8.4.99.tar.gz
  md5: 611ab2460cb23f1b54f28ed19f1d8689

build:
  number: 1
  entry_points:
    - astrotool = pwkit.cli.astrotool:commandline
    - casatask = pwkit.environments.casa.tasks:commandline
    - imtool = pwkit.cli.imtool:commandline
    - latexdriver = pwkit.cli.latexdriver:commandline
    - pkcasascript = pwkit.environments.casa.scripting:commandline
    - pkenvtool = pwkit.environments:commandline
    - wrapout = pwkit.cli.wrapout:commandline

requirements:
  build:
    - numpy
    - pathlib # [py2k]
    - python
    - setuptools
    - six

  run:
    - numpy
    - pathlib # [py2k]
    - python
    - six

test:
  imports:
    - pwkit

about:
  home: https://github.com/pkgw/pwkit/
  license: MIT License
  summary: Miscellaneous scientific and astronomical tools.
