# Copyright 2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# For some reason this package's setup.py only installs the package as an .egg
# file with a .pth. I find this setup kind of annoying, but whatever.

package:
  name: bibtexparser
  version: "0.6.2"

source:
  fn: bibtexparser-0.6.2.tar.gz
  url: https://pypi.python.org/packages/7c/29/cf7341bb488577cd593d07d658cc0b8228e60caf9c5d709fddb1e1892ce2/bibtexparser-0.6.2.tar.gz
  md5: b173b4d1d770dcac929dca2c19ed3f2a

build:
  number: 0

requirements:
  build:
    - pyparsing
    - python
    - setuptools

  run:
    - pyparsing
    - python

test:
  imports:
    - bibtexparser

about:
  home: https://bibtexparser.readthedocs.org/
  license: LGPLv3 or BSD
  summary: A module for parsing BibTeX files.
