# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: wcslib
  version: "5.12"

source:
  fn: wcslib-5.12.tar.bz2
  url: http://www.atnf.csiro.au/pub/software/wcslib/wcslib-5.12.tar.bz2
  sha256: 50ff182920541bea156e7f53588cdfba1754b1bdcd0bc64a136a5d124af98de4

build:
  number: 4
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cfitsio
    - pgplot
  run:
    - cfitsio
    - libgfortran 3.0.0 #[linux]
    - pgplot

about:
  home: http://www.atnf.csiro.au/people/mcalabre/WCS/wcslib/
  license: GPL version 3
  summary: library for World Coordinate System computations
