# Copyright 2015-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# NOTE: if updating major or minor version, update `so-versioning.patch`.

package:
  name: casa-casacore
  version: "2.1.0"

source:
  fn: v2.1.0.tar.gz
  url: https://github.com/casacore/casacore/archive/v2.1.0.tar.gz
  sha256: 9c0017e741c1c4b14bc09582867910f750cd76ff2673e0ecd554aa5b2db7acb4
  patches:
    - default-root.patch
    - ncursesw.patch

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - boost
    - cfitsio
    - cmake
    - fftw
    - hdf5 >=1.8.15.1
    - ncurses
    - nomkl # speeds up by avoiding big download
    - numpy
    - openblas
    - readline
    - wcslib
  run:
    - boost
    - cfitsio
    - fftw
    - hdf5 >=1.8.15.1
    - libgfortran 3.0.0  # [linux]
    - ncurses
    - numpy
    - openblas
    - readline
    - wcslib

about:
  home: https://github.com/casacore
  license: GPL version 2
  summary: core libraries for CASA
