{% set name = "tectonic" %}
{% set version = "0.1.5" %}
{% set sha256 = "9680a2d989ee5014769936e6d566caa232c874e8ad566ffa2f419cb309871051" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://crates.io/api/v1/crates/{{ name }}/{{ version }}/download
  sha256: {{ sha256 }}

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - rust-toolchain
    - cargo
    - fontconfig 2.12.*  # [not osx]
    - freetype 2.7|2.7.*
    - graphite2 1.3.*
    - harfbuzz 1.4.*  # note: conda-forge pins 1.3, but we need 1.4
    - icu 58.*
    - libpng >=1.6.28,<1.7
    - openssl 1.0.*
    - zlib 1.2.*
  run:
    - fontconfig 2.12.*  # [not osx]
    - freetype 2.7|2.7.*
    - graphite2 1.3.*
    - harfbuzz 1.4.*
    - icu 58.*
    - libpng >=1.6.28,<1.7
    - openssl 1.0.*
    - zlib 1.2.*

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - tectonic --help

about:
  home: https://github.com/pkgw/tectonic/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A modernized, complete, standalone TeX/LaTeX engine.'

extra:
  recipe-maintainers:
    - pkgw
