# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: at-spi2-atk
  version: "2.18.1"

source:
  fn: at-spi2-atk-2.18.1.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/at-spi2-atk/2.18/at-spi2-atk-2.18.1.tar.xz
  sha256: c4b15f9386d34d464ddad5f6cc85669742c016df87141ceee93513245979c12d

build:
  number: 2
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - at-spi2-core
    - atk
    - dbus-client
    - glib
    - gobject-introspection
    - python
  run:
    - at-spi2-core
    - atk
    - dbus-client
    - glib
    - gobject-introspection

about:
  home: http://www.gtk.org/
  license: LGPL
  summary: bridge for AT-SPI and ATK accessibility technologies
