# Copyright 2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "wsclean" %}
{% set version = "2.4" %}
{% set sha256 = "0174a0f06b4e2e43af027d879cb9064d50d09fbfde25c788ab5a0ac97e49059f" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://downloads.sourceforge.net/project/{{ name }}/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - osx.patch  # [osx]

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cmake
    - boost 1.63.*
    - casacore 2.2.*
    - fftw 3.3.*
    - gsl 2.2.*
  run:
    - boost 1.63.*
    - casacore 2.2.*
    - fftw 3.3.*
    - gsl 2.2.*

about:
  home: http://wsclean.sourceforge.net/
  license: GPLv3
  summary: fast, widefield interferometric imaging
