# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: cfitsio
  version: "3.370"

source:
  fn: cfitsio3370.tar.gz
  url: ftp://heasarc.gsfc.nasa.gov/software/fitsio/c/cfitsio3370.tar.gz
  md5: abebd2d02ba5b0503c633581e3bfa116

build:
  number: 3
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS
  
requirements:
  build:

about:
  home: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
  license: LGPL
  summary: a library for reading and writing FITS files
