# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: gobject-introspection
  version: 1.51.1

source:
  fn: gobject-introspection-1.51.1.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/gobject-introspection/1.51/gobject-introspection-1.51.1.tar.xz
  sha256: 2c47e7632df936055b4e96f48315e2d392be10a0642ce11610fba5240e19772d
  patches:
    - hugepaths.patch

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cairo
    - gettext  # [osx]
    - glib 2.51.*
    - libffi 3.2.*
    - python
  run:
    - glib 2.51.*
    - libffi 3.2.*

about:
  home: https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
  license: LGPL
