# This can't go in conda-forge since it takes too long to build on the CI
# machines. That could be worked around but I'm really not eager to undertake
# that.

{% set name = "rust-toolchain" %}
{% set version = "1.17.0" %}
{% set sha256 = "4baba3895b75f2492df6ce5a28a916307ecd1c088dc1fd02dbfa8a8e86174f87" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: rustc-{{ version }}-src.tar.gz
  url: https://static.rust-lang.org/dist/rustc-{{ version }}-src.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  detect_binary_files_with_prefix: true
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - bison
    - cmake
    - flex
    - python >=2.7,<3
    - toolchain
    - m2w64-toolchain  # [win]
    - posix  # [win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.rust-lang.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: 'A fast, safe, productive systems programming language.'

extra:
  recipe-maintainers:
    - pkgw
