# Copyright 2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: pyraf
  version: "2.1.10"

source:
  fn: pyraf-2.1.10.tar.gz
  url: http://stsdas.stsci.edu/download/pyraf/pyraf-2.1.10.tar.gz
  sha256: 040085e0de7d509701bd8aaa9d2abf16f7c3a5db655a2a78a43252c143b20199

build:
  number: 1
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - d2to1
    - iraf
    - modern-xorg-stack
    - numpy
    - python
    - setuptools
    - stsci_distutils
    - stsci_tools
  run:
    - iraf
    - modern-xorg-stack
    - numpy
    - python
    - stsci_tools

about:
  home: http://www.stsci.edu/institute/software_hardware/pyraf
  license: BSD
  summary: A Python-based IRAF command language.
