# Copyright 2015-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: rpfits
  version: "2.23"

source:
  fn: rpfits-2.23.tar.gz
  url: http://www.atnf.csiro.au/pub/software/rpfits/rpfits-2.23.tar.gz
  md5: 197407a6b463e8d8f40040075a3983a3

build:
  number: 6
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  run:
    - libgfortran 3.0.0 #[linux]

about:
  home: http://www.atnf.csiro.au/computing/software/rpfits.html
  license: unspecified
  summary: library for reading and writing a FITS-like data format
