# Copyright 2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: aipy
  version: "2.1.1"

source:
  fn: v2.1.1.tar.gz
  url: https://github.com/HERA-Team/aipy/archive/v2.1.1.tar.gz
  sha256: 6c49afab713355edc227e02862aa72a13d2b0c4f2aa83da8622d19fe7b98a8dd

build:
  number: 1
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - astropy
    - ephem
    - numpy
    - python
    - setuptools

  run:
    - astropy
    - ephem
    - numpy
    - python

test:
  imports:
    - aipy

about:
  home: https://github.com/HERA-Team/aipy
  license: GPL v2+
  summary: Astronomical interferometry in Python
