# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# NOTE: if updating major or minor version, update `so-versioning.patch`.
# Build on CentOS 5.

# XXX VERSION PINS REMOVED FOR conda-forge FOR NOW

package:
  name: casa-tools
  version: "4.6.0"

source:
  svn_url: https://svn.cv.nrao.edu/svn/casa/branches/release-4_6/
  svn_rev: 36590
  svn_ignore_externals: yes
  patches:
    - so-versioning.patch
    - casaroot.patch
    - no-java.patch
    - mydbus.patch
    - ncursesw.patch

build:
  number: 4
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - boost
    - casa-casacore 2.1.*
    - cmake
    - dbus-cxx
    - dbus
    - fftw
    - gsl
    - libgfortran 3.0.0 #[linux]
    - libsakura 2.0.0
    - libxml2
    - libxslt
    - ncurses
    - nomkl # speeds by avoiding big download
    - openblas
    - pgplot
    - readline
    - rpfits
    - qt4 4.8.*
    - qwt5
    - xerces-c28
  run:
    - boost
    - casa-casacore 2.1.*
    - dbus-cxx
    - dbus
    - fftw
    - gsl
    - libgfortran 3.0.0 #[linux]
    - libsakura 2.0.0
    - libxml2
    - libxslt
    - ncurses
    - openblas
    - pgplot
    - readline
    - rpfits
    - qt4 4.8.*
    - qwt5
    - xerces-c28

about:
  home: http://casa.nrao.edu/
  license: GPLv2
  summary: scientific tool implementations for CASA
